const menu = [
    {
        id: 1,
        title: "Super breakfast",
        category: "Breakfast",
        price: 14.99,
        img: "./images/breakfast1.jpg",
        desc: "Pão integral, pasta de azeitona, tomate seco, queijos e azeitona e suco de laranja.",
    },
    {
        id: 2,
        title: "Super breakfast",
        category: "Breakfast",
        price: 14.99,
        img: "./images/breakfast2.jpg",
        desc: "Pão integral, pasta de azeitona, tomate seco, queijos e azeitona e suco de laranja.",
    },
    {
        id: 3,
        title: "Super breakfast",
        category: "Breakfast",
        price: 14.99,
        img: "./images/breakfast3.jpg",
        desc: "Pão integral, pasta de azeitona, tomate seco, queijos e azeitona e suco de laranja.",
    },
    {
        id: 4,
        title: "Super breakfast",
        category: "Breakfast",
        price: 14.99,
        img: "./images/breakfast4.jpg",
        desc: "Pão integral, pasta de azeitona, tomate seco, queijos e azeitona e suco de laranja.",
    },
    {
        id: 5,
        title: "Super breakfast",
        category: "Dessert",
        price: 14.99,
        img: "./images/dessert1.jpg",
        desc: "Pão integral, pasta de azeitona, tomate seco, queijos e azeitona e suco de laranja.",
    },
    {
        id: 6,
        title: "Super breakfast",
        category: "Dessert",
        price: 14.99,
        img: "./images/dessert2.jpg",
        desc: "Pão integral, pasta de azeitona, tomate seco, queijos e azeitona e suco de laranja.",
    },
    {
        id: 7,
        title: "Super breakfast",
        category: "Dinner",
        price: 14.99,
        img: "./images/dinner1.jpg",
        desc: "Pão integral, pasta de azeitona, tomate seco, queijos e azeitona e suco de laranja.",
    },
    {
        id: 8,
        title: "Super breakfast",
        category: "Dinner",
        price: 14.99,
        img: "./images/dinner2.jpg",
        desc: "Pão integral, pasta de azeitona, tomate seco, queijos e azeitona e suco de laranja.",
    },
    {
        id: 9,
        title: "Super breakfast",
        category: "Lunch",
        price: 14.99,
        img: "./images/lunch1.jpg",
        desc: "Pão integral, pasta de azeitona, tomate seco, queijos e azeitona e suco de laranja.",
    },
    {
        id: 10,
        title: "Super breakfast",
        category: "Lunch",
        price: 14.99,
        img: "./images/lunch2.jpg",
        desc: "Pão integral, pasta de azeitona, tomate seco, queijos e azeitona e suco de laranja.",
    },
    {
        id: 11,
        title: "Super breakfast",
        category: "Lunch",
        price: 14.99,
        img: "./images/lunch3.jpg",
        desc: "Pão integral, pasta de azeitona, tomate seco, queijos e azeitona e suco de laranja.",
    },
    {
        id: 12,
        title: "Super breakfast",
        category: "Lunch",
        price: 14.99,
        img: "./images/lunch4.jpg",
        desc: "Pão integral, pasta de azeitona, tomate seco, queijos e azeitona e suco de laranja.",
    },
];